language: rust
rust:
  - stable
cache: cargo
env:
- FEAT=stm32l0x1,rt
matrix:
  fast_finish: true
script:
  - rustup target add thumbv6m-none-eabi
  - cargo build --release --examples --features $FEAT
  