language: rust
rust:
  - stable
  - nightly
cache: cargo
env:
- MCU=stm32l0x1
- MCU=stm32l0x2
# STM32L062 is not being run, as it's currently identical to STM32L082
- MCU=stm32l082
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup target add thumbv6m-none-eabi
script:
  - RUSTFLAGS="-D warnings" cargo build --release --examples --features rt,$MCU
