language: rust
rust:
  - stable
  - nightly
cache: cargo
env:
- MCU=stm32l0x1
- MCU=stm32l0x2
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt
  - rustup target add thumbv6m-none-eabi
script:
  - cargo fmt -- --check
  - RUSTFLAGS="-D warnings" cargo build --release --examples --features rt,$MCU
