[package]
edition = "2018"
authors = [
    "Arko <arko2600@gmail.com>",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Peripheral access API for STM32L0 series microcontrollers"
documentation = "https://docs.rs/crate/stm32l0xx-hal"

keywords = [
    "arm",
    "cortex-m",
    "stm32l0xx",
    "stm32",
    "stm32l0",
    "hal",
]
license = "0BSD"
name = "stm32l0xx-hal"
readme = "README.md"
repository = "https://github.com/stm32-rs/stm32l0xx-hal"
version = "0.0.1"

[package.metadata.docs.rs]
features = ["stm32l011", "rt"]

[dependencies]
bare-metal = { version = "0.2.4", features = ["const-fn"] }
cast = { version = "0.2.2", default-features = false }
cortex-m = "0.5.8"
cortex-m-rt = "0.6.7"
embedded-hal = { version = "0.2.2", features = ["unproven"] }
nb = "0.1.1"
void = { version = "1.0.2", default-features = false }

# [dependencies.stm32l0]
# version = "0.6.0"
# features = ["stm32l0x1", "rt"]

[dependencies.stm32l0]
path = "../stm32-rs-arko/stm32l0"
features = ["stm32l0x1", "rt"]

[dev-dependencies]
panic-halt = "0.2.0"

[features]
device-selected = []
rt = ["stm32l0/rt"]
stm32l011 = ["stm32l0/stm32l0x1", "device-selected"]

[profile.dev]
debug = true

[profile.release]
debug = true
opt-level = "s"
