[package]
edition = "2018"
authors = [
    "Arko <arko2600@gmail.com>",
]
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
description = "Peripheral access API for STM32L0 series microcontrollers"
documentation = "https://docs.rs/crate/stm32l0xx-hal"

keywords = [
    "arm",
    "cortex-m",
    "stm32l0xx",
    "stm32",
    "stm32l0",
    "hal",
]
license = "0BSD"
name = "stm32l0xx-hal"
readme = "README.md"
repository = "https://github.com/stm32-rs/stm32l0xx-hal"
version = "0.0.1"

[package.metadata.docs.rs]
features = ["stm32l0x1", "rt"]

[dependencies]
bare-metal = { version = "0.2.4", features = ["const-fn"] }
cast = { version = "0.2.2", default-features = false }
cortex-m = "0.5.8"
cortex-m-rt = "0.6.7"
cortex-m-semihosting = "0.3.1"
embedded-hal = { version = "0.2.2", features = ["unproven"] }
nb = "0.1.1"
void = { version = "1.0.2", default-features = false }

#[dependencies.stm32l0]
#version = "0.6.0"
#features = ["stm32l0x1", "rt"]

# Dev fork of stm32-rs: https://github.com/arkorobotics/stm32-rs
# -- Note: Rename "stm32-rs" to "stm32-rs-arko" or path below
[dependencies.stm32l0]
path = "../stm32-rs-arko/stm32l0"
features = ["stm32l0x1", "rt"]

[dev-dependencies]
cortex-m-rt = "0.6.7"
cortex-m-semihosting = "0.3.2"
panic-halt = "0.2.0"
panic-semihosting = "0.5.1"
cortex-m-rtfm = "0.4.0"

[features]
default = ["rt"]
rt = ["stm32l0/rt"]
stm32l0x1 = ["stm32l0/stm32l0x1"]

[profile.dev]
codegen-units = 1
incremental = false
debug = true
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
debug = true
opt-level = "s"
